#pragma once



// Wszystkie tekstury posiadaja 4znakowe nazwy tak, aby ladnie uk³ada³a siê mapa.

#define flor 0 * 2 + 0
#define tree 0 * 2 + 1
#define wall 1 * 2 + 0
#define door 1 * 2 + 1
#define monk 2 * 2 + 0
#define enmy 2 * 2 + 1

const int level1[] =
{
	wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall,
	wall, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, tree, tree, tree, tree, tree, wall,	flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, tree, tree, tree, tree, tree, wall,
	wall, flor, flor, tree, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, tree, tree, tree, tree, wall,	flor, flor, flor, tree, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, tree, tree, tree, tree, wall,
	wall, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, tree, tree, wall,	flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, tree, tree, wall,
	wall, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, tree, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, tree, tree, wall,	flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, tree, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, tree, tree, wall,
	wall, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, monk, flor, flor, flor, tree, tree, wall,	flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, monk, flor, flor, flor, tree, tree, wall,
	wall, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, tree, wall,	flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, tree, wall,
	wall, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, tree, wall,	flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, tree, wall,
	wall, flor, flor, flor, flor, flor, flor, flor, flor, tree, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, door,	flor, flor, flor, flor, flor, flor, flor, flor, flor, tree, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,
	wall, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,	flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,
	wall, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,	flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,
	wall, flor, flor, flor, flor, flor, flor, flor, flor, monk, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,	flor, flor, flor, flor, flor, flor, flor, flor, flor, monk, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,
	wall, flor, flor, tree, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, tree, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,	flor, flor, flor, tree, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, tree, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,
	wall, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,	flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,
	wall, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,	flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,
	wall, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,	flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,
	wall, flor, flor, flor, flor, flor, flor, flor, flor, tree, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,	flor, flor, flor, flor, flor, flor, flor, flor, flor, tree, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,
	wall, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,	flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,
	wall, flor, flor, tree, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,	flor, flor, flor, tree, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,
	wall, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,	flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,
	wall, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, tree, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,	flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, tree, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,
	wall, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, monk, monk, monk, monk, wall,	flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, monk, flor, flor, flor, flor, flor, wall,
	wall, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,	flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,
	wall, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,	flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,
	wall, flor, flor, flor, flor, flor, flor, flor, flor, tree, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, door,	flor, flor, flor, flor, flor, flor, flor, flor, flor, tree, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,
	wall, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,	flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,
	wall, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,	flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,
	wall, flor, flor, flor, flor, flor, flor, flor, flor, monk, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,	flor, flor, flor, flor, flor, flor, flor, flor, flor, monk, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,
	wall, flor, flor, tree, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, tree, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,	flor, flor, flor, tree, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, tree, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,
	wall, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,	flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,
	wall, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, tree, flor, flor, flor, flor, wall,	flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,
	wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall,	wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall,

};

const int level2[] =
{
	wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall,
	wall, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall, flor, flor, flor, flor, flor, flor, flor, wall, flor, flor, flor, flor, wall, flor, flor, tree, tree, tree, tree, tree, wall,	flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, tree, tree, tree, tree, tree, wall,
	wall, flor, flor, tree, flor, flor, flor, flor, flor, flor, wall, flor, flor, flor, flor, flor, flor, flor, wall, flor, flor, flor, flor, wall, flor, flor, flor, tree, tree, tree, tree, wall,	flor, flor, flor, tree, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, tree, tree, tree, tree, wall,
	wall, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall, flor, flor, flor, flor, flor, flor, flor, wall, flor, flor, flor, flor, door, flor, flor, flor, flor, flor, tree, tree, wall,	flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, tree, tree, wall,
	wall, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall, flor, flor, flor, flor, flor, tree, flor, wall, flor, flor, flor, flor, wall, flor, flor, flor, flor, flor, tree, tree, wall,	flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, tree, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, tree, tree, wall,
	wall, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall, flor, flor, flor, flor, flor, flor, flor, wall, flor, flor, flor, flor, wall, flor, flor, flor, flor, flor, tree, tree, wall,	flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, monk, flor, flor, flor, tree, tree, wall,
	wall, flor, flor, flor, flor, flor, flor, flor, flor, flor, door, flor, flor, flor, flor, flor, flor, flor, door, flor, flor, flor, flor, wall, flor, flor, flor, flor, flor, flor, tree, wall,	flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, tree, wall,
	wall, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall, flor, flor, flor, flor, flor, flor, flor, wall, flor, flor, flor, flor, wall, flor, flor, flor, flor, flor, flor, tree, wall,	flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, tree, wall,
	wall, flor, flor, flor, flor, flor, flor, flor, flor, tree, wall, flor, flor, flor, flor, flor, flor, flor, wall, flor, flor, flor, flor, wall, flor, flor, flor, flor, flor, flor, flor, door,	flor, flor, flor, flor, flor, flor, flor, flor, flor, tree, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,
	wall, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall, flor, flor, flor, flor, flor, flor, flor, wall, flor, flor, flor, flor, wall, flor, flor, flor, flor, flor, flor, flor, wall,	flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,
	wall, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall, flor, flor, flor, flor, flor, flor, flor, wall, flor, flor, flor, flor, wall, flor, flor, flor, flor, flor, flor, flor, wall,	flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,
	wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, flor, flor, flor, flor, wall, flor, flor, flor, flor, flor, flor, flor, wall,	flor, flor, flor, flor, flor, flor, flor, flor, flor, monk, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,
	wall, flor, flor, tree, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, tree, flor, flor, wall, flor, flor, flor, flor, wall, flor, flor, flor, flor, flor, flor, flor, wall,	flor, flor, flor, tree, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, tree, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,
	wall, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall, flor, flor, flor, flor, wall, wall, wall, wall, wall, wall, wall, wall, wall,	flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,
	wall, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall, flor, flor, flor, flor, wall, flor, flor, flor, flor, flor, flor, flor, wall,	flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,
	wall, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall, flor, flor, flor, flor, wall, flor, flor, flor, flor, flor, flor, flor, wall,	flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,
	wall, flor, flor, flor, flor, flor, flor, flor, flor, tree, flor, flor, flor, flor, flor, flor, flor, flor, wall, flor, flor, flor, flor, wall, flor, flor, flor, flor, flor, flor, flor, door,	flor, flor, flor, flor, flor, flor, flor, flor, flor, tree, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,
	wall, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, door, flor, flor, flor, flor, wall, flor, flor, flor, flor, flor, flor, flor, wall,	flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,
	wall, flor, flor, tree, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall, flor, flor, flor, flor, wall, flor, flor, flor, flor, flor, flor, flor, wall,	flor, flor, flor, tree, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,
	wall, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall, flor, flor, flor, flor, wall, flor, flor, flor, flor, flor, flor, flor, wall,	flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,
	wall, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, tree, flor, wall, flor, flor, flor, flor, wall, flor, flor, flor, flor, flor, flor, flor, wall,	flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, tree, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,
	wall, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall,	flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, monk, flor, flor, flor, flor, flor, wall,
	wall, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,	flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,
	wall, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,	flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,
	wall, flor, flor, flor, flor, flor, flor, flor, flor, tree, flor, flor, flor, flor, flor, wall, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, door,	flor, flor, flor, flor, flor, flor, flor, flor, flor, tree, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,
	wall, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,	flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,
	wall, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, door, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,	flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,
	wall, flor, flor, flor, flor, flor, flor, flor, flor, monk, flor, flor, flor, flor, flor, wall, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,	flor, flor, flor, flor, flor, flor, flor, flor, flor, monk, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,
	wall, flor, flor, tree, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,	flor, flor, flor, tree, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, tree, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,
	wall, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,	flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,
	wall, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, tree, flor, flor, flor, flor, wall,	flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, flor, wall,
	wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall,	wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall, wall,

};
